spring:
    application:
        name: secret
    datasource:
        url: secret
        username: secret
        password: secret
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

#logging:
#    level:
#        sql: debug
#        org.hibernate.orm.jdbc.bind: trace
